spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://127.0.0.1:5433/yugabyte?user=yugabyte&password=yugabyte "
    username: "yugabyte"
    password: "yugabyte"
  jpa:
    hibernate:
      ddl-auto: "update"

logging:
  level:
    org:
      hibernate:
        SQL: "debug"
        type:
          descriptor:
            sql: "trace"
